In [ ]:
"""""
# 1.
7 // 2  # → 3  (division entière)
7 %  2  # → 1  (reste / modulo)

# 2.
2 ** 10 # → 1024

# 3. Permutation en une ligne (unpacking)
a, b = b, a

# 4.
x = 10; x += 3  # x = 13
x *= 2            # x = 26

# 5.  3/2 → 1.5 (float),  3//2 → 1 (int)
"""

In [ ]:
prenom = input("Votre prénom : ")
age    = int(input("Votre âge : "))
annee  = 2025 - age

print(f"Bonjour {prenom}, vous êtes né(e) en {annee}.")
print(f"Âge  : {age:>3}") # aligné à droite sur 3 caractères
print(f"Âge  : {age:<3}") # aligné à gauche sur 3 caractères
print(f"Année: {annee:5d}") # aligné à droite sur 5 caractères, avec des espaces devant si besoin
print(f"Année: {annee:04d}") # affiché sur 4 chiffres, avec des zéros devant si besoin

In [ ]:

# 1.
type(3.0)   # float
type(3)     # int
type("3")   # str
type(True)  # bool

# 2. True vaut 1, False vaut 0 → résultat = 2
True + True + False  # → 2

# 3. Valeurs "falsy"
bool(0)   # False
bool("")  # False
bool([])  # False
bool(-1)  # True  (tout entier ≠ 0 est truthy)

# 4. Nombres complexes
z = 3 + 4j
z.real   # → 3.0
z.imag   # → 4.0
abs(z)   # → 5.0  (√(3²+4²))

# 5. None est retourné quand aucun return n'est explicite
def f(): pass
print(f())  # → None


In [ ]:

s = "Bonjour le Monde!"

len(s)                   # → 18
s[11:16]                # → "Monde"
s.upper()               # → "BONJOUR LE MONDE!"
s.lower()               # → "bonjour le monde!"
s.replace("Monde", "Python")  # → "Bonjour le Python!"
s.startswith("Bon")    # → True
s.split()               # → ['Bonjour', 'le', 'Monde!']
s[::-1]                 # → "!ednoM el ruojnoB"


In [ ]:

notes = [14, 8, 17, 12, 9, 15]

notes.append(11)          # [14,8,17,12,9,15,11]
notes.insert(2, 10)       # [14,8,10,17,12,9,15,11]
notes.remove(8)           # supprime le premier 8
# del notes[3]            # supprime l'élément d'indice 3 (17)
# del notes[1:4]         # supprime les éléments d'indice 1 à 3 (8,10,17)
#pour supprimer un element a partir de sa valeur, on utilise remove, pour supprimer un element a partir de son indice, on utilise del
#pour supprimer la neme occurence d'une valeur, on peut faire une boucle while qui utilise remove tant que la valeur est présente dans la liste exemple:

notes.sort()               # ordre croissant
notes.sort(reverse=True)  # ordre décroissant
print(notes)             # → [17, 15, 14, 12, 11, 9]
notes[5]+=1                   # incrémente la note d'indice 5 de 1
print(notes)             # → [17, 15, 14, 12, 11, 10]

while 11 in notes:
     notes.remove(11)  # supprime toutes les occurrences de 11
print(notes)             # → [17, 15, 14, 12, 9, 10]
moyenne = sum(notes) / len(notes)

t = tuple(notes)           # tuple immuable
print(t)                 # → (17, 15, 14, 12, 9, 10)
notes[-1]                  # dernier élément


In [ ]:
# 1. Mention
note = float(input("Note : "))
if   note >= 16: print("Excellent")
elif note >= 14: print("Bien")
elif note >= 12: print("Assez Bien")
elif note >= 10: print("Passable")
else:            print("Insuffisant")

# 2. Année bissextile
# Une année est bissextile si elle est divisible par 4 mais pas par 100, ou si elle est divisible par 400.
a = int(input("Année : "))
bis = (a % 4 == 0 and a % 100 != 0) or (a % 400 == 0)
print("Bissextile" if bis else "Non bissextile")

# 3. Expression ternaire
n = int(input("Nombre : "))
signe = "positif" if n > 0 else ("négatif" if n < 0 else "nul")
print(signe)

In [ ]:
# 1. Nombres pairs
for i in range(2, 21, 2): print(i)

# 2. Factorielle
n = int(input("n = "))
fact = 1
for i in range(1, n+1): fact *= i

# 3. Table de 7
for i in range(1, 11):
    print(f"7 × {i} = {7*i}")

# 4. Prénoms commençant par 'A'
prenoms = ["Alice", "Bob", "Anna", "Clara"]
for p in prenoms:
    if p.startswith("A"): print(p)

# 5. Maximum sans max()
lst = [3, 7, 1, 9, 4]
maxi = lst[0]
for x in lst:
    if x > maxi: maxi = x

# 6. enumerate()
for idx, val in enumerate(lst):  #enumarate sert à obtenir à la fois l'indice et la valeur d'une liste lors d'une boucle for
    print(f"[{idx}] = {val}")
#on peut s en servir aussi pour parcourir une chaîne de caractères ou un dictionnaire exemple:
s = "Python"
for idx, char in enumerate(s):
    print(f"Caractère {idx} : {char}")


In [ ]:

# 1. Premier
def est_premier(n):
    if n < 2: return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return False
    return True

# 2. Statistiques
def statistiques(notes):
    return min(notes), max(notes), sum(notes)/len(notes)
def statistiques2(notes):
    return {
        "min": min(notes),
        "max": max(notes),
        "moy": sum(notes) / len(notes)
    }

a,b,c = statistiques(notes=[2,5,12,16])
print(f"min={a} max={b} moy={c}")
(x,y,z) = statistiques(notes=[2,5,12,16])
print(f"min={x} max={y} moy={z}")
[az,by,cz] = statistiques(notes=[2,5,12,16])
print(f"min={az} max={by} moy={cz}")
dico={"min":None,"max":None,"moy":None};print(dico)
dico.update(statistiques2(notes=[2, 5, 12, 16]));print(dico)

# 3. Récursion
def factorielle(n):
    if n <= 1: return 1
    return n * factorielle(n - 1)

# 4. Paramètre par défaut
def saluer(nom, politesse="Bonjour"):
    print(f"{politesse}, {nom} !")
saluer("Alice")               # Bonjour, Alice !
saluer("Bob", "Bonsoir")      # Bonsoir, Bob !

# 5. Variable locale vs globale
compteur = 0  # globale
def incrementer():
    global compteur
    compteur += 1
incrementer(); print(compteur)  # → 1

noms = ["Alice", "Bob", "Charlie"]
notes = [12, 15, 8]

dico = dict(zip(noms, notes))
x= noms @ note
print(dico)


min=2 max=16 moy=8.75
min=2 max=16 moy=8.75
min=2 max=16 moy=8.75
{'min': None, 'max': None, 'moy': None}
{'min': 2, 'max': 16, 'moy': 8.75}
Bonjour, Alice !
Bonsoir, Bob !
1
{'Alice': 12, 'Bob': 15, 'Charlie': 8}


In [5]:

# 1. Carrés
carres = [x**2 for x in range(1, 11)]

# 2. Nombres impairs (filtre avec if)
lst = [1,2,3,4,5,6]
impairs = [x for x in lst if x % 2 != 0]

# 3. Tuples (i, i²)
pairs = [(i, i**2) for i in range(1, 6)]

# 4. Mots en majuscules
phrase = "bonjour le monde"
mots = [m.upper() for m in phrase.split()]

# 5. Compréhension de dictionnaire
d = {n: n**2 for n in range(1, 6)}
# → {1:1, 2:4, 3:9, 4:16, 5:25}

print(carres)
print(impairs)
print(pairs)
print(mots)
print(d)
listepairs = [i for i in range(0, 11, 2)];print(listepairs)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 3, 5]
[(1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]
['BONJOUR', 'LE', 'MONDE']
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
[0, 2, 4, 6, 8, 10]


In [42]:
noms = ["Alice", "Bob", "Charlie"]
notes = [12, 15, 8]
print(zip(noms, notes))  # → <zip object at 0x...>
print(list(zip(noms, notes)))  # → [('Alice', 12), ('Bob', 15), ('Charlie', 8)]
print(dict(zip(noms, notes))) # → {'Alice': 12, 'Bob': 15, 'Charlie': 8}
print(tuple(zip(noms, notes))) # → (('Alice', 12), ('Bob', 15), ('Charlie', 8))
print(tableau := list(zip(noms, notes)))  # affectation dans une expression (Python 3.8+)
print(tableau[2]) # → ('Charlie', 8) #pour extraire charlie de ce tuble :
print(tableau[2][0]) # → 'Charlie'

dico = {nom: note for nom, note in zip(noms, notes)}
print(dico)
# {'Alice': 12, 'Bob': 15, 'Charlie': 8}

[('Alice', 12), ('Bob', 15), ('Charlie', 8)]
{'Alice': 12, 'Bob': 15, 'Charlie': 8}
(('Alice', 12), ('Bob', 15), ('Charlie', 8))
[('Alice', 12), ('Bob', 15), ('Charlie', 8)]
('Charlie', 8)
Charlie
{'Alice': 12, 'Bob': 15, 'Charlie': 8}


In [ ]:
import numpy as np

# 1.
np.zeros(10);print(np.zeros(10))  # → [0., 0., ..., 0.]
np.full(5, 7);print(np.full(5, 7))  # → [7, 7, 7, 7, 7]

#la valeur propre et le vecteur propre d'une matrice correspondent à des scalaires et des vecteurs qui caractérisent les propriétés d'une matrice.
#  La valeur propre (eigenvalue) est un scalaire λ tel que pour un vecteur propre (eigenvector) v non nul, la relation suivante est vérifiée : A * v = λ * v, où A est la matrice en question.
#  Les valeurs propres donnent des informations sur la nature de la transformation linéaire représentée par la matrice, tandis que les vecteurs propres indiquent les directions dans lesquelles cette transformation agit de manière simple (en étirant ou en compressant).
#  Ces concepts sont fondamentaux en algèbre linéaire et ont de nombreuses applications en physique, en ingénierie et en sciences des données.

# 2.
np.arange(0, 21);print(np.arange(0, 21))                  # [0, 1, ..., 20]
np.linspace(0, 1, 5) ;print(np.linspace(0, 1, 5))            # [0., 0.25, 0.5, 0.75, 1.]

# 3. Vectorisation
a = np.array([1, 4, 9, 16, 25])
np.sqrt(a);print(np.sqrt(a))                       # → [1., 2., 3., 4., 5.]

# 4. Matrices
np.eye(3)  ;print(np.eye(3))                       # identité 3×3
np.random.rand(2, 3)   ;print(np.random.rand(2, 3))          # aléatoire 2×3

# 5. Multiplication matricielle
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A, B)   # ou A @ B


# 6. Statistiques
t = np.array([10, 20, 30, 40])
x,y,z= (t.mean(), t.max(), t.std())
print(x,y,z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[7 7 7 7 7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0.   0.25 0.5  0.75 1.  ]
[1. 2. 3. 4. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.78414045 0.73102045 0.9338899 ]
 [0.69428801 0.87120276 0.62381122]]
25.0 40 11.180339887498949


In [49]:
import numpy as np

classe = {
    "Alice": [14, 16, 12],
    "Bob":   [9,  11, 8 ],
    "Clara": [18, 17, 19]
}

def moyenne(notes):
    return np.mean(notes)

def mention(m):
    if   m >= 16: return "Très Bien"
    elif m >= 14: return "Bien"
    elif m >= 12: return "Assez Bien"
    elif m >= 10: return "Passable"
    else:         return "Insuffisant"

# Affichage + recherche du meilleur
meilleures = {}
for nom, notes in classe.items():
    m = moyenne(notes)
    meilleures[nom] = m
    print(f"{nom} : {m:.1f} — {mention(m)}")

# Meilleur étudiant
best = max(meilleures, key=lambda k: meilleures[k]) #permet de trouver la clé du dictionnaire qui correspond à la valeur maximale
#ca fonctionne en parcourant toutes les clés du dictionnaire "meilleures" et en comparant les valeurs associées à ces clés grâce à la fonction lambda qui prend une clé k et retourne la valeur correspondante meilleures[k]. La clé qui correspond à la valeur maximale sera retournée et stockée dans la variable best.
#mais je prefere get; il cherche dans meilleurs la plus grande clé en comparant les valeurs de chaque cle

best = max(meilleures, key=meilleures.get)

print(f"\nMeilleur : {best} avec {meilleures[best]:.1f}")

# Admis (≥12) par compréhension
admis = [n for n, m in meilleures.items() if m >= 12]
print("Admis :", admis)

# Moyenne générale
toutes = np.concatenate(list(classe.values())) #concatène toutes les listes de notes en un seul tableau
print(toutes)
print(f"Moyenne classe : {np.mean(toutes):.2f}")

Alice : 14.0 — Bien
Bob : 9.3 — Insuffisant
Clara : 18.0 — Très Bien

Meilleur : Clara avec 18.0
Admis : ['Alice', 'Clara']
[14 16 12  9 11  8 18 17 19]
Moyenne classe : 13.78


In [ ]:
#liste de 100 à 0
li= list(range(100, 1, -1));print(li) 
li=li[::2];print(li)


[100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2]
[100, 98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


In [ ]:
import numpy as np

#Exercice 1
print("Ecrivez la taille n, p de votre matrice A ")
nA= int(input("nA "))
pA= int(input("pA"))
print("Ecrivez la taille n, p de votre matrice B ")
nB= int(input("nB "))
pB= int(input("pB"))
print(f"Votre matrice A est de taille [{nA}, {pA}]")


Ecrivez la taille n, p de votre matrice A 
Ecrivez la taille n, p de votre matrice B 
Votre matrice A est de taille [1, 1]


In [ ]:
import numpy as np

# ===========================================================================
# UTILITAIRES
# ===========================================================================

def afficher_matrice(A, nom="M"):
    """Affiche joliment une matrice NumPy avec son nom."""
    n, m = A.shape
    print(f"  {nom} ({n}x{m}) =")
    for ligne in A:
        print("   ", [round(x, 4) for x in ligne])
    print()

# ===========================================================================
# PROBLÈME — Matrice Magique
# ===========================================================================

def est_magique(M):

    n, m = M.shape
    assert n == m, "La matrice doit être carrée."

    # Étape 1 : constante magique = somme de la première ligne
    constante = M[0].sum()

    # Étape 2 : vérification de TOUTES les lignes
    if not np.all(M.sum(axis=1) == constante):
        return False

    # Étape 3 : vérification de TOUTES les colonnes
    if not np.all(M.sum(axis=0) == constante):
        return False

    # Étape 4 : diagonale principale
    if np.trace(M) != constante:
        return False

    # Étape 5 : diagonale anti-principale
    if np.trace(np.fliplr(M)) != constante:
        return False

    return True

# --- TESTS ---
print("=" * 60)
print("PROBLÈME — Matrice Magique")
print("=" * 60)

M_mag     = np.array([[8, 1, 6],
                       [3, 5, 7],
                       [4, 9, 2]])

M_non_mag = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

M_mag4    = np.array([[16,  2,  3, 13],
                       [ 5, 11, 10,  8],
                       [ 9,  7,  6, 12],
                       [ 4, 14, 15,  1]])

afficher_matrice(M_mag,     "M_magique_3x3")
print(f"  est_magique(M_mag)     = {est_magique(M_mag)}")      # True

print()
afficher_matrice(M_non_mag, "M_non_magique")
print(f"  est_magique(M_non_mag) = {est_magique(M_non_mag)}")  # False

print()
afficher_matrice(M_mag4,    "M_magique_4x4 (Dürer)")
print(f"  est_magique(M_mag4)    = {est_magique(M_mag4)}")     # True

PROBLÈME — Matrice Magique
  M_magique_3x3 (3x3) =
    [np.int64(8), np.int64(1), np.int64(6)]
    [np.int64(3), np.int64(5), np.int64(7)]
    [np.int64(4), np.int64(9), np.int64(2)]

  est_magique(M_mag)     = True

  M_non_magique (3x3) =
    [np.int64(1), np.int64(2), np.int64(3)]
    [np.int64(4), np.int64(5), np.int64(6)]
    [np.int64(7), np.int64(8), np.int64(9)]

  est_magique(M_non_mag) = False

  M_magique_4x4 (Dürer) (4x4) =
    [np.int64(16), np.int64(2), np.int64(3), np.int64(13)]
    [np.int64(5), np.int64(11), np.int64(10), np.int64(8)]
    [np.int64(9), np.int64(7), np.int64(6), np.int64(12)]
    [np.int64(4), np.int64(14), np.int64(15), np.int64(1)]

  est_magique(M_mag4)    = True
